### ISSUE TITLE
GDK (Unity) Associate with Microsoft Store Not Working

### ISSUE THREAD

**Issue by stonstad** [microsoft/gdk-unity-package#129]
I'm following Microsoft's tutorial (https://developer.microsoft.com/en-us/games/xbox/docs/gdk/gdk-unity-end-to-end-guide) for Unity GDK setup instructions. This is a Microsoft tool.

I am attempting to associate my game with the Microsoft Store.  

GDK -> Associate with the Microsoft Store -> Assocaite with the Microsoft Store -> Next -> Sign In

Screenshot: https://i.imgur.com/S2oaLJf.png

The sign-in link doesn't do anything. I can confirm opening a browser window from this workflow does work, as there is a previous link to open a help document and it works. It is the sign-in link that won't open.

**Comment by edwarduwms** [comment]
Hi

Thanks for reaching out. 

Could you please share the GDK version you are using?

Regards

**Comment by stonstad** [comment]
Hi @Edwarduwms!  I had an old version of the GDK and I didn't realize it.  I downloaded the June update and the association workflow with the store works.  Thank you!
