### ISSUE TITLE
Link to GDK should point to aka.ms/gdk or aka.ms/gdkdl should be redirected to https://github.com/microsoft/GDK/releases

### ISSUE THREAD

**Issue by rbeesley** [microsoft/gdk-unity-package#43]
Currently in the README.md it points to aka.ms/gdkdl, but with the Windows 11 announcement today the GDK isn't restricted to partners and can be obtained from aka.ms/gdk, or aka.ms/gdkdl should be pointed to https://github.com/microsoft/GDK/releases instead so that the most recent version is consistent. The latter fix is probably a better way to address it so all stale links of aka.ms/gdkdl are updated, but it would require tracking down the owner of the alias and I'm not sure how someone externally could file a bug against that...

**Comment by payzer** [comment]
Great point! We'll get that updated.

**Comment by rbeesley** [comment]
The GDK still has a reference to aka.ms/gdkdl, so maybe just fixing this documentation is the best.
