### ISSUE TITLE
Support for RealTimeActivity XblUserStatisticsTrackStatistics?

### ISSUE THREAD

**Issue by cgfred** [microsoft/gdk-unity-package#60]
Hi!

We don't seem to find a way to access the XblUserStatisticsTrackStatistics feature in the current package, we need this to be able to know when a leaderboard has actually been updated on the server side as it appears it can take some time.

Is this already implemented? If yes, how do we access it?

If no, then what is the guestimate when it will/could be added?

**Comment by tculotta** [comment]
This has been added in #88 and will be included in the upcoming next week
