### ISSUE TITLE
0x87DD0005 Can’t login to Xbox Live

### ISSUE THREAD

**Issue by Dukembg** [microsoft/gdk-unity-package#70]
Completely stuck...

> I've imported the unity GDK package https://github.com/microsoft/gdk-unity-package/releases

> Installed GDK https://github.com/microsoft/GDK/releases/tag/June_2021_Update_4

> Reserved my app

> Setup XBox live services for desktop only

> Granted myself access to the test 
environment

> Published the test environment

> Associated my unity project with the store

> Switched to the sandbox ( Shows an error, but when I launch apps, It shows I'm in the sandbox )

> Launched Apps and shows I'm in the sandbox

> Set Windows to developer mode in settings

Can't login... screenshots attached..
![5A15CFE7-7D2B-4873-9FEB-59642D9EA67C](https://user-images.githubusercontent.com/98967543/152374845-ef0074ad-d33e-40c2-a5aa-223efbf82d55.jpeg)

Got an email saying that my app has access to my account. Says unverified. Attached screenshot.
![3CD72FB1-636B-41A7-A9DF-149C48426F02](https://user-images.githubusercontent.com/98967543/152375013-81d69ebe-97ca-40e8-bac0-410a3461f8b8.png)

**Comment by payzer** [comment]
Thank you for posting your question. Unfortunately, this plugin is not compatible with the Creators Program. In case it is helpful, Xbox Live is no longer required to submit your game as part of the Creators Program.

**Comment by Dukembg** [comment]
> Thank you for posting your question. Unfortunately, this plugin is not compatible with the Creators Program. In case it is helpful, Xbox Live is no longer required to submit your game as part of the Creators Program.

Thanks for your quick response. How would one go about testing their APIs?

**Comment by payzer** [comment]
Which DRM features? I'm less familiar with the DRM APIs myself, but can ask around.

**Comment by Dukembg** [comment]
> Which DRM features? I'm less familiar with the DRM APIs myself, but can ask around.

https://docs.microsoft.com/en-us/gaming/gdk/_content/gc/commerce/pc-specific-considerations/xstore-basic-drm-and-license-checks

Just a the basic for starters

**Comment by payzer** [comment]
Thank you for the link. For those APIs, from what I can tell you don't need Xbox Live, only a license and a user. An easier way to test them might be to not switch sandbox (you can go back to retail) and use your normal store account. 

But you likely will need to publish your game to the store and download it as part of the testing workflow: https://docs.microsoft.com/en-us/gaming/gdk/_content/gc/commerce/getting-started/xstore-product-testing-setup. For publishing you would need additional permissions. The GDK is public, but the publishing process would be through a program like ID@Xbox.
