### ISSUE TITLE
Plugin fails to load DLLs/Tools for public GDK installs

### ISSUE THREAD

**Issue by tculotta** [microsoft/gdk-unity-package#93]
For anyone receiving this message "Could not find the GDK DLLs. Make sure you have the Microsoft GDK installed.": we've found that the registry keys differ for the GDK-only install (i.e. installed from GitHub). A fix will be included in the next release, but in the meantime, you can fix this yourself by changing the three calls to GetRegKey() with "InstallPath" to use "GRDKInstallPath" instead in [GdkUtilities.cs](https://github.com/microsoft/gdk-unity-package/blob/4d8f12956fe9ba1d8de28fded69e8d38ea44f8df/Package/Assets/GDK-Tools/Source/Utilities/GdkUtilities.cs)

**Comment by chrisjenningsunity** [comment]
This worked perfect! Thanks

**Comment by tculotta** [comment]
Fixed in #101 and included in the [latest release](https://github.com/microsoft/gdk-unity-package/releases/tag/2207.1).
